### ISSUE TITLE
Getting it to work with Python3

### ISSUE THREAD

**Issue by kootenpv** [rsteca/sklearn-deap#1]
Is `copy_reg` really necessary? It is not available on Python 3. Do you think it could be made in a compatible way?

**Comment by rsteca** [comment]
In python 3 the library has been renamed to copyreg instead of copy_reg. I used it in order to be able to use multiprocessing, it's like a little hack. I'm not sure if it's necessary in python 3. If you want to adapt the code to python 3 and make a pull request, you are welcome :)

**Comment by kootenpv** [comment]
It runs according to your suggestion :) https://github.com/kootenpv/sklearn-deap/commit/ae094c56b83fbcb261f5b0420a1809222a25448a

**Comment by rsteca** [comment]
Looks great, I already merged the pull request, thanks @kootenpv
