### ISSUE TITLE
best_score_ and best_params_ never get updated when error score is negative

### ISSUE THREAD

**Issue by zickyzazang** [rsteca/sklearn-deap#12]
Some Sklearn scoring functions return negative error scores (e.g. mean absolute error) to stick to the "bigger is better" paradigm. However, with this error score the following code block never is evaluated True 

`if current_best_score_ > self.best_score_:
    self.best_score_ = current_best_score_
    self.best_params_ = current_best_params_`

and the best_score, and more importantly the best_params stay -1 and None respectively.

Setting self.best_score_ with -inf or with a much smaller value would sort of solve the issue. Setting best_score with current_best_score in the first generation would be a better solution imo

**Comment by rsteca** [comment]
Solved in #13
