### ISSUE TITLE
What's wrong with my datas ?

### ISSUE THREAD

**Issue by langju** [rsteca/sklearn-deap#16]
With the following code 👍 
 paramgrid = {"n_jobs": -1,
             "max_features":['auto','log2'],
             "n_estimators":[10,100,500,1000],
             "min_samples_split" : [2,5,10],
             "max_leaf_nodes" : [1,5,10,20,50] }

#min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None

cv = EvolutionaryAlgorithmSearchCV(estimator=RandomForestClassifier(),
                                   params=paramgrid,
                                   scoring="accuracy",
                                   cv=StratifiedKFold(y, n_folds=10),
                                   verbose=True,
                                   population_size=50,
                                   gene_mutation_prob=0.10,
                                   tournament_size=3,
                                   generations_number=10
                                  )

cv.fit(X, y)

and having the followning error :

TypeErrorTraceback (most recent call last)
<ipython-input-56-887d5f96a05f> in <module>()
     20                                   )
     21 
---> 22 cv.fit(X,y)

/root/anaconda2/lib/python2.7/site-packages/evolutionary_search/__init__.pyc in fit(self, X, y)
    276         self.best_params_ = None
    277         for possible_params in self.possible_params:
--> 278             self._fit(X, y, possible_params)
    279         if self.refit:
    280             self.best_estimator_ = clone(self.estimator)

/root/anaconda2/lib/python2.7/site-packages/evolutionary_search/__init__.pyc in _fit(self, X, y, parameter_dict)
    301         toolbox = base.Toolbox()
    302 
--> 303         name_values, gene_type, maxints = _get_param_types_maxint(parameter_dict)
    304         if self.gene_type is None:
    305             self.gene_type = gene_type

/root/anaconda2/lib/python2.7/site-packages/evolutionary_search/__init__.pyc in _get_param_types_maxint(params)
     33     types = []
     34     for _, possible_values in name_values:
---> 35         if isinstance(possible_values[0], float):
     36             types.append(param_types.Numerical)
     37         else:

TypeError: 'int' object has no attribute '__getitem__'

**Comment by langju** [comment]
note that all my datas are numeric

**Comment by ryanpeach** [comment]
```
paramgrid = {"n_jobs": -1,
"max_features":['auto','log2'],
"n_estimators":[10,100,500,1000],
"min_samples_split" : [2,5,10],
"max_leaf_nodes" : [1,5,10,20,50] }
```

"n_jobs" is referencing an integer, not a list of integers.

```
paramgrid = {"n_jobs": [-1],
"max_features":['auto','log2'],
"n_estimators":[10,100,500,1000],
"min_samples_split" : [2,5,10],
"max_leaf_nodes" : [1,5,10,20,50] }
```

Will fix it.

**Comment by ryanpeach** [comment]
Issue can be closed.

**Comment by langju** [comment]
thanks. indeed idiot question :)
