### ISSUE TITLE
Sklearn Depreciation

### ISSUE THREAD

**Issue by ryanpeach** [rsteca/sklearn-deap#20]
cross_validation has been replaced with model_selection and will soon be depreciated. Already getting a warning. Tried to simply change this but they have moved a few other things around and also changed how some functions seem to fundamentally work.

**Comment by rsteca** [comment]
Yes, I already tried to use model_selection but it seems like a lot of things should be changed in order for it to work. If you are able to do it, please add it to your pull request or do a new one. Thanks.

**Comment by ryanpeach** [comment]
I have a different branch locally I will work on the issue with, so it will be a separate pull request. My current pull request is mostly just to add cv_results_ which was necessary for a project I was working on for compatibility with the other model selection methods in sklearn. I would like to improve that as well by passing individual_members instead to cv_results_ for a more detailed output. I'll keep you updated as I'm sure I will use these functionalities a lot, model selection is at the heart of almost everything and this package is much more useful than sklearn's gridsearch or randomizedsearch.

**Comment by kootenpv** [comment]
I also work with my own heavily adapted copy. I'll post the git gist, perhaps @ryanpeach has something much better. In my case, I feel like I created a pretty nasty copy.

https://gist.github.com/kootenpv/42674b319c346932ce4d3cec9c337142

**Comment by ryanpeach** [comment]
I have fixed this issue entirely in my recent pull request. Along with some major upgrades.

**Comment by ryanpeach** [comment]
The coming push will fix your issue, I hope. At least it does on my end :)

**Comment by rsteca** [comment]
fixed on #19
