### ISSUE TITLE
warning message-i got these warning messages, dont know how to solve this

### ISSUE THREAD

**Issue by rabiam04** [rsteca/sklearn-deap#25]
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

**Comment by rsteca** [comment]
Which version of the library you have installed?

**Comment by rabiam04** [comment]
solved
