### ISSUE TITLE
It stucks

### ISSUE THREAD

**Issue by KOLANICH** [rsteca/sklearn-deap#46]
After an initial fit in a few iterations a strange thing occurs.

1 bad variants (with the lowest fitness) reappear after were eliminated.
2 neither maximum fitness raises, nor the average one or the minimum one.
in my case it got its maximum fitnes in a single iteration, and the rest 99 were just eating my money for just accelerating global warming and thermal death of the universe.

I'm not familiar with deap but I wonder if
1 should mating instances choice probability be a function of their fitnesses?
2 isn't there a bug in mating function? Shouldn't the variables be saved and the new ones be generated from the saved ones.
3 shouldn't they be sampled not from integers (both mutation and mating)?
4 shouldn't mated instances produce 2*<number of attrs> children and themselves, which are not only randomly sampled, but also the average of every attr of a pair preserving the rest of?
5 shouldn't the worst instances be eliminated from population?
6 shouldn't it take distributions, like RandomizedSearchCV rather than instances and sample from the distributions

I'm not going to research this topic for now, I have a lot of work to do and it's your library anyway.

**Comment by rsteca** [comment]
If you think that you can improve the library, you are welcome to do a pull request. All the points you mentioned are fair and deserve some research.

**Comment by ryanpeach** [comment]
I don't think any of these issues are related to our library, rather they have to do with DEAP. You should query their repo for specifics on how the genetic algorithms work.

**Comment by KOLANICH** [comment]
Issues int the functions defined in sklearn-deap are definitely related to sklearn-deap.
