### ISSUE TITLE
Doubts about encoding correctness

### ISSUE THREAD

**Issue by olologin** [rsteca/sklearn-deap#5]
I have some doubts about current parameter encoding (to chromosome) correctness.

Let's assume that we have 2 categorical parameters f1 and f2:

	Enc f1  f2
	0000 a 1
	0001 a 2
	0010 a 3
	0011 a 4
	0100 a 5
	0101 b 1
	0110 b 2
	0111 b 3
	1000 b 4
	1001 b 5
	1010 c 1
	1011 c 2
	1100 c 3
	1101 c 4
	1110 c 5

If we use any crossover operator, for example let's do 2 points crossover between some points:

	(a, 4) 0011    0111 (b, 3)
		        x
	(c, 3) 1100    1000 (b, 4)

After crossover we've got b, but both parents don't have b as first parameter.

**Comment by rsteca** [comment]
That's interesting. Any ideas on how to enhance the encoding of the parameters or the crossover so this doesn't happen?

**Comment by olologin** [comment]
I've rewritten your code, i'll give a link to my version soon.

I encoded each value of a parameter as separate integer.
i.e. in above case f1 is encoded by int's set(0, 1, 2), (a, b, c correspondingly), f2 is encoded by set(0,1,2,3,4)
examples of genome - [0, 3] (a, 4), [2, 2] (c, 3)

**Comment by rsteca** [comment]
Cool, I would like to see that pull request :)

**Comment by olologin** [comment]
@rsteca take a look at this https://github.com/olologin/sklearn-deap/blob/encoding_fix/evolutionary_search/__init__.py
It works, but:
1. Looks like multiprocessing is not working.
2. I changed your interface a little bit (constructor now has additional parameters)

**Comment by rsteca** [comment]
It looks great, make a pull request and I will check why multiprocessing is not working.

What version of scikit-learn are you using? I see you changed some imports like this one:
```
from sklearn.model_selection._search import BaseSearchCV
```

**Comment by olologin** [comment]
@rsteca, last developer version from master branch, they are moving all model selection related stuff to sklearn.model_selection, but they didn't export BaseSearchCV, that's why i imported it in such ugly way.

**Comment by rsteca** [comment]
Solved in #6
